### ISSUE TITLE
Замечания по программе Vector

### ISSUE THREAD

**Issue by alexey-malov** [maria-kanyushkova/OOP#7]
https://github.com/maria-kanyushkova/OOP/blob/227bfb864f781d52ad503915bf2e0a172d8777a9/src/main/java/lab2/vector/Main.java#L27-L35

- [x] Scanner является Closeable объектом и должен быть закрыт (используйте try-with-resources)

**Comment by maria-kanyushkova** [comment]
https://github.com/maria-kanyushkova/OOP/issues/7#issue-585712619
поправлено

**Comment by alexey-malov** [comment]
https://github.com/maria-kanyushkova/OOP/blob/7460fbf815781826d7b99fad2ece2e610bd01458/src/main/java/lab2/vector/ProcessVector.java#L8-L16

- [ ] По заданию надо модифицировать переданный массив вместо возвращения нового

**Comment by alexey-malov** [comment]
- [ ] Добавить тест, обрабатывающий пустой массив
